POST 45.12.6.133:8080/api/customer/job
Content-Type: application/json

{
  "startDate": "1665323342",
  "endDate": "1665406405",
  "status": "new_task",
  "title": "hackatoooon",
  "executorId": 1,
  "lon": 56.868903,
  "lat": 42.035278,
  "customerId": 1,
  "requiredVehicle": {
    "characteristic": "Погрузчик_Вилочный_Диз_3т/6м",
    "model": "KOMATSU FD30T-17"
  }
}



###

PUT localhost:8080/api/customer/job
Content-Type: application/json

{
  "jobId": 5,
  "startDate": "1665323342",
  "endDate": "1665406405",
  "status": "new_task",
  "title": "hackatoooon",
  "executorId": 1,
  "lon": 56.868903,
  "lat": 42.035278,
  "customerId": 1,
  "requiredVehicle": {
    "characteristic": "Погрузчик_Вилочный_Диз_3т/6м",
    "model": "KOMATSU FD30T-17"
  }
}

###
DELETE localhost:8080/api/customer/job

{
 "id": 4
}

###
GET localhost:8080/api/customer/jobs

