POST localhost:8080/api/customer/job
Content-Type: application/json

{
  "customerId": 1,
  "endDate": 0,
  "id": 0,
  "lat": 0,
  "lon": 0,
  "requiredVehicle": {
    "type": "Автовышка (28 м)",
    "model": "Чайка Сервис 2784SG"
  },
  "startDate": 0,
  "status": "string",
  "title": "string"
}


###

PUT localhost:8080/api/customer/job
Content-Type: application/json

{
  "customerId": 1,
  "endDate": 0,
  "executorId": 0,
  "id": 1,
  "lat": 0,
  "lon": 0,
  "requiredVehicle": {
    "type": "Погрузчик_Вилочный_Диз_3т/6м",
    "model": "KOMATSU FD30T-17"
  },
  "startDate": 0,
  "status": "string",
  "title": "string"
}

###
DELETE localhost:8080/api/customer/job

{
 "id": 4
}

###
GET 45.12.6.133:8080/api/customer/jobs

###
GET localhost:8080/api/addCustomer

###
POST localhost:8080/api/signIn
Content-Type: application/json

{
  "login": "customer0",
  "password": "0000",
  "type": "customer"
}

###
GET localhost:8080/api/updateVehicles

###

GET localhost:8080/api/customer/jobs

###
GET localhost:8080/api/executor/jobs/1